USE studdb8;
DROP TABLE IF EXISTS Hus;
CREATE TABLE Hus(
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
adresse VARCHAR(50) NOT NULL,
latitude FLOAT NOT NULL,
longitude FLOAT NOT NULL,
beskrivelse TEXT NOT NULL,
etasjer INTEGER NOT NULL
);